USE [master]
GO
/* DROP DATABASE IF EXISTS [MedicalHistory] */
/****** Object:  Database [MedicalHistory]    Script Date: 2023/02/15 15:37:56 ******/
CREATE DATABASE [MedicalHistory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MedicalHistory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MedicalHistory.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MedicalHistory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MedicalHistory_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [MedicalHistory] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MedicalHistory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MedicalHistory] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MedicalHistory] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MedicalHistory] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MedicalHistory] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MedicalHistory] SET ARITHABORT OFF 
GO
ALTER DATABASE [MedicalHistory] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MedicalHistory] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MedicalHistory] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MedicalHistory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MedicalHistory] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MedicalHistory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MedicalHistory] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MedicalHistory] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MedicalHistory] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MedicalHistory] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MedicalHistory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MedicalHistory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MedicalHistory] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MedicalHistory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MedicalHistory] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MedicalHistory] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MedicalHistory] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MedicalHistory] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MedicalHistory] SET  MULTI_USER 
GO
ALTER DATABASE [MedicalHistory] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MedicalHistory] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MedicalHistory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MedicalHistory] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MedicalHistory] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MedicalHistory] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MedicalHistory] SET QUERY_STORE = ON
GO
ALTER DATABASE [MedicalHistory] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [MedicalHistory]
GO
EXEC sp_changedbowner 'sa';
GO
/****** Object:  Table [dbo].[Doctor]    Script Date: 2023/02/15 15:37:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Doctor](
	[personId] [uniqueidentifier] NOT NULL DEFAULT (NEWID()),
	[phone] [nvarchar](255) NULL,
	[email] [nvarchar](255) NULL,
 CONSTRAINT [PK__Doctor__EC7D7D4D0AA3288C] PRIMARY KEY CLUSTERED 
(
	[personId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dose]    Script Date: 2023/02/15 15:37:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dose](
	[id] [uniqueidentifier] NOT NULL DEFAULT (NEWID()),
	[description] [nvarchar](255) NULL,
 CONSTRAINT [PK_Dose] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Medication]    Script Date: 2023/02/15 15:37:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medication](
	[id] [uniqueidentifier] NOT NULL DEFAULT (NEWID()),
	[name] [nvarchar](255) NULL,
 CONSTRAINT [PK__Medicati__3213E83F9040A2FD] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Patient]    Script Date: 2023/02/15 15:37:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patient](
	[personId] [uniqueidentifier] NOT NULL DEFAULT (NEWID()),
	[phone] [nvarchar](255) NULL,
	[email] [nvarchar](255) NULL,
 CONSTRAINT [PK__Patient] PRIMARY KEY CLUSTERED 
(
	[personId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 2023/02/15 15:37:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[id] [uniqueidentifier] NOT NULL DEFAULT (NEWID()),
	[name] [nvarchar](255) NULL,
	[surname] [nvarchar](255) NULL,
 CONSTRAINT [PK__Person] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Prescription]    Script Date: 2023/02/15 15:37:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prescription](
	[id] [uniqueidentifier] NOT NULL DEFAULT (NEWID()),
	[medicationId] [uniqueidentifier] NULL,
	[visitId] [uniqueidentifier] NULL,
	[startdate] [datetime] NULL,
	[endate] [datetime] NULL,
	[cancelledDate] [datetime] NULL,
	[doseId] [uniqueidentifier] NULL,
 CONSTRAINT [PK__Prescription] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Visit]    Script Date: 2023/02/15 15:37:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Visit](
	[id] [uniqueidentifier] NOT NULL DEFAULT (NEWID()),
	[patientId] [uniqueidentifier] NULL,
	[doctorId] [uniqueidentifier] NULL,
	[date] [datetime] NULL,
 CONSTRAINT [PK_Visit] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_Person] FOREIGN KEY([personId])
REFERENCES [dbo].[Person] ([id])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_Person]
GO
ALTER TABLE [dbo].[Person]  WITH CHECK ADD  CONSTRAINT [FK_Person_Doctor] FOREIGN KEY([id])
REFERENCES [dbo].[Doctor] ([personId])
GO
ALTER TABLE [dbo].[Person] CHECK CONSTRAINT [FK_Person_Doctor]
GO
ALTER TABLE [dbo].[Prescription]  WITH CHECK ADD  CONSTRAINT [FK__Prescript__medic__60A75C0F] FOREIGN KEY([medicationId])
REFERENCES [dbo].[Medication] ([id])
GO
ALTER TABLE [dbo].[Prescription] CHECK CONSTRAINT [FK__Prescript__medic__60A75C0F]
GO
ALTER TABLE [dbo].[Prescription]  WITH CHECK ADD  CONSTRAINT [FK_Prescription_Dose] FOREIGN KEY([doseId])
REFERENCES [dbo].[Dose] ([id])
GO
ALTER TABLE [dbo].[Prescription] CHECK CONSTRAINT [FK_Prescription_Dose]
GO
ALTER TABLE [dbo].[Prescription]  WITH CHECK ADD  CONSTRAINT [FK_Prescription_Patient] FOREIGN KEY([visitId])
REFERENCES [dbo].[Patient] ([personId])
GO
ALTER TABLE [dbo].[Prescription] CHECK CONSTRAINT [FK_Prescription_Patient]
GO
ALTER TABLE [dbo].[Prescription]  WITH CHECK ADD  CONSTRAINT [FK_Prescription_Visit] FOREIGN KEY([visitId])
REFERENCES [dbo].[Visit] ([id])
GO
ALTER TABLE [dbo].[Prescription] CHECK CONSTRAINT [FK_Prescription_Visit]
GO
ALTER TABLE [dbo].[Visit]  WITH CHECK ADD  CONSTRAINT [FK_Visit_Doctor] FOREIGN KEY([doctorId])
REFERENCES [dbo].[Doctor] ([personId])
GO
ALTER TABLE [dbo].[Visit] CHECK CONSTRAINT [FK_Visit_Doctor]
GO
ALTER TABLE [dbo].[Visit]  WITH CHECK ADD  CONSTRAINT [FK_Visit_Patient] FOREIGN KEY([patientId])
REFERENCES [dbo].[Patient] ([personId])
GO
ALTER TABLE [dbo].[Visit] CHECK CONSTRAINT [FK_Visit_Patient]
GO
USE [master]
GO
ALTER DATABASE [MedicalHistory] SET  READ_WRITE 
GO
